# Generated by Django 5.2.8 on 2025-12-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
